language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install pytest pytest-cov codecov
# command to run tests
script:
  - pytest -v --cov=. smx.py
after_success:
  - codecov
